### ISSUE TITLE
Windows distributable can't find local image referenced by css

### ISSUE THREAD

**Issue by mhuggins** [nos/client#212] opened 2018-06-09 15:25 UTC
## Expected Behavior
Run `yarn dist` on Windows, and launch the executable.  You should see the background image (`auth-background.png`, a checkerboard-like pattern) in the background of the authentication screen.

## Current Behavior
The Chrome console shows a `net::ERR_FILE_NOT_FOUND` error when trying to load the image file (see screenshot below).

![windows-file-not-found](https://user-images.githubusercontent.com/169093/41193198-a0b117fe-6bce-11e8-87ac-8e86af01fa90.png)

## Possible Solution
It appears that the `/static` path is being included twice, and so the relative pathing is not working correctly.  Note that this works properly on macOS, so simply changing the relative path will likely not be a viable solution.

A possible solution probably involves some webpack change related to the way we load sass to ensure pathing works on both macOS and Windows.  One idea is to use the [`includePaths`](https://github.com/webpack-contrib/sass-loader) option for sass-loader.

## Steps to Reproduce (for bugs)
1. On Windows, run `yarn dist`.
2. Launch the generated executable.
3. Observe the error message in Chrome console.

## Context
For now, just the auth background image is not available on Windows.  As we continue to develop, this will be a growing problem as more images are references from SCSS files.

## Your Environment
* Version used: `develop` branch
* Environment name and version: Any
* Operating System and version: Windows

**Comment by trueinsider** [comment] 2018-06-21 00:20
Is this still relevant? I did steps to reproduce and this is what I see:
![image](https://user-images.githubusercontent.com/662644/41691107-851d6da8-7501-11e8-8c01-a88e0261b9e2.png)
There is checkerboard-like pattern. Unfortunately, I don't know how to open console in dist.

**Comment by DalderupMaurice** [comment] 2018-07-10 18:31
This was actually fixed a long time ago (Can't find the PR) 
Due to the changes made to the browser/moving to electron-webpack etc the issue does not occur anymore

FYI: you can open console log by editing the index file of the main process :P 
There `installExtensions` is only executed in dev mode - remove the if statement and you have dev tools on dist builds

**Closed by DalderupMaurice** 2018-07-10 18:31 UTC
Labels: bug, community issue
