### ISSUE TITLE
Upon being disconnected from the network, the nOS Client should automatically try to reconnect every x seconds

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#638] opened 2018-10-14 10:41 UTC
## Describe the solution you'd like and the expected behavior
Upon being disconnected from the network, the nOS Client should automatically try to reconnect every x seconds

## Is your feature request related to a problem? Please describe.
You have to go to settings select another network and reselect the previous network to be able to reconnect to the network.

## Possible implementation / References
/

## Additional context
/

**Comment by mhuggins** [comment] 2018-10-14 16:01
Duplicate of #554.

**Closed by mhuggins** 2018-10-14 16:01 UTC
Labels: community issue, enhancement
