### ISSUE TITLE
nOS Client not allowing to login after clicking on  create account

### ISSUE THREAD

**Issue by coded9** [nos/client#128] opened 2018-05-06 10:08 UTC
Cannot click on login button after clicking on create account 
## Expected Behavior
Clicking on login should redirect to login page
## Current Behavior
After clicking on register ,nOS client hangs and not allows the user to click/enter anything

## Possible Solution
May be extensive testing required on windows and support for latest versions is needed.

## Steps to Reproduce (for bugs)
1.Open nOS client
2.Click on create account
3.Try to click on login
https://drive.google.com/open?id=1YlEqtyUNJ3NwDs5-pFNxpZMuV_FNGM45

## Context
This is a basic functionality,login functionality should work ideally

## Your Environment

* Version used:
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0):
* Operating System and version (desktop or mobile):windows desktop
* node js : 8.11.1
* yarn : 1.6.0 
* npm : 6.0.0

**Comment by deanpress** [comment] 2018-05-06 13:31
Able to reproduce. The issue is that `-webkit-app-region: drag;` is applied to `.LoginLayout` styling.

**Comment by deanpress** [comment] 2018-05-06 13:33
Closed as it's a duplicate issue: https://github.com/nos/client/issues/124

**Closed by deanpress** 2018-05-06 13:33 UTC
