### ISSUE TITLE
Can not add new custom network 

### ISSUE THREAD

**Issue by kaxax** [nos/client#602] opened 2018-09-30 02:28 UTC
## Expected Behavior

With Nos browser i want to add new custom network.

## Current Behavior

**But when i go to setting on browser, there's error on console .**

`C:\Users\User\Desktop\hakathon\nos-client\node_modules\react\node_modules\prop-types\checkPropTypes.js:19 Warning: Failed prop type: The prop `allNetworks` is marked as required in `NetworkSettings`, but its value is `null .....`.

**when i try to add new custom network , following errors is logged.**

**First one**
`NetworkSettings.js?ddef:111 Uncaught TypeError: Cannot read property 'find' of null
    at NetworkSettings._this.handleConfirmAddNetwork (NetworkSettings.js?ddef:111)
    at eval (DialogPresenter.js?e10e:65) .....
`

**And second one**

`Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information...`

## Your Environment
* nOS Client version used:
* Environment name and version
    * Node version:  8.12.0
    * NPM version: 6.4.1
    * Yarn version: 1.10.1
* Operating System and version (desktop or mobile): Windows 7

**Comment by mhuggins** [comment] 2018-09-30 04:09
Thanks for reporting!  Looks like this is a duplicate of #356, but the additional log info will be helpful for tracking it down. ❤️

**Closed by mhuggins** 2018-09-30 04:09 UTC

**Comment by DalderupMaurice** [comment] 2018-09-30 07:13
Just to have some additional data, you signed in with your WIF, right?
