### ISSUE TITLE
Prevent browser tabs to grow passed application width

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#187] opened 2018-05-28 16:49 UTC
## Expected Behavior

Not sure yet - cap amount of tabs or group them? 
Might want to discuss the expected behavior first in discord or here

## Current Behavior

The tabs grow passed the application width, enforcing people to scroll horizontally

## Possible Solution

- Cap the amount of tabs allowed
- Group tabs
(Must be discussed first) 

## Screenshot
![](https://i.imgur.com/7088mNO.png)

## Steps to Reproduce (for bugs)

1. Click 1000 times on the "New tab" button

## Context

Prevent browser tabs to grow passed application width to prevent horizontal scrolling

## Your Environment

* Version used:
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0):
* Operating System and version (desktop or mobile):
any

**Comment by mhuggins** [comment] 2018-05-28 17:13
I think we should consider implementing one or both of the following:

1. Set a min-width on the tabs, and once there are enough tabs opened to justify it, make the tabs scroll horizontally.  This might not be ideal for desktop users since mouse wheels don't generally scroll horizontally though.
1. Set a max number of tabs and just disable the "Add" button when we reach that limit.  For comparison, I tried opening a bunch of tabs in Chrome and found that they opened indefinitely, but I ultimately ran into memory usage issues where I would have been better off with a max limit. 😆

**Comment by DalderupMaurice** [comment] 2018-05-28 17:59
I'm not a fan of horizontal scrolling :P

**Comment by mmoshi** [comment] 2018-05-31 07:47
Looks like a duplicate of https://github.com/nos/client/issues/164, can probably be closed.

**Comment by DalderupMaurice** [comment] 2018-05-31 08:04
Actually not, the tabs are now responsive but are still able to grow beyond the application it's width @mmoshi

**Closed** 2018-06-16 13:35 UTC
Labels: bug, community issue, enhancement
